spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    datasource:
        url: jdbc:mysql://localhost:13306/board?useSSL=false&serverTimezone=Asia/Seoul
        username: snow
        password: snow
        driver-class-name: com.mysql.cj.jdbc.Driver
